# Generated by Django 4.2.1 on 2023-05-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
