# Generated by Django 4.2.1 on 2023-05-15 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('data_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('publishing_house', models.CharField(max_length=255, verbose_name='Издательство')),
                ('year_publishing', models.DateField(blank=True, null=True, verbose_name='Год издания')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_book', to='book.author')),
                ('genre_id', models.ManyToManyField(related_name='genre_book', to='book.genre')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_book', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
