# Generated by Django 4.2.1 on 2023-05-16 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_reader_alter_book_year_publishing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='data_birth',
            new_name='date_birth',
        ),
    ]
